### ISSUE TITLE
Add degrees to which the panels will go at what times, user chooses date

### ISSUE THREAD

**Issue by PHPirates** [PHPirates/SolArduino#17]

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
Done - angleGraph branch.

**Comment by slideclimb** [comment]
^GitHub bug...
