### ISSUE TITLE
Change toast 'Panels stopped/not moving' to 'Panels stopped'

### ISSUE THREAD

**Issue by PHPirates** [PHPirates/SolArduino#42]
Seems like stopped and not moving are synonyms in this context, so one of them is redundant.

**Comment by PHPirates** [comment]
Comes from the [Arduino](http://192.168.8.42/?panel=stop).

**Comment by slideclimb** [comment]
- [ ] upload code to arduino to change message in android app

**Comment by PHPirates** [comment]
@slideclimb I'll just change it then on master, if you just take the trouble to add a task here ;)
