### ISSUE TITLE
Add option to plan storm-mode ahead

### ISSUE THREAD

**Issue by PHPirates** [PHPirates/SolArduino#46]

**Comment by slideclimb** [comment]
**Arduino**

- [x] remember if panels were in auto mode 
    - [x] if auto mode: switch back to auto mode afterwards (at end time)
    - [x] if not auto mode: set panels at angle it was before
        - [x] remember angle
- [x] remember begin and start time
- [x] set panel to 0 at start time
- [x] only switch to storm mode at start time
- [x] when moving panels while in storm mode, go out of storm mode
- [x] add to update response if storm mode active or not
- [ ] uncomment // TODO UNCOMMENT things before actually using

**Comment by slideclimb** [comment]
**Android**

- [x] convert date/time to time in **seconds** since 1970
- [x] send request ```/?stormstart=----------&stormend=----------```
    - [x] times in url are ```UnixTime[] + 3600``` when calculating with MMa
- [x] resend request when changing start or end time
- [ ] should get from update request if storm mode active

**Comment by slideclimb** [comment]
**Desktop**

- [ ] convert date/time to time in **seconds** since 1970
- [ ] send request ```/?stormstart=----------&stormend=----------```
    - [ ] times in url are ```UnixTime[] + 3600``` when calculating with MMa

**Comment by PHPirates** [comment]
Moved to a note in the GitHub Project because of too low priority.
